In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('electronics_products_pricing.csv')

In [4]:
display(df)

,id,prices.availability,prices.condition,prices.currency,prices.dateSeen,prices.isSale,prices.merchant,prices.shipping,prices.sourceURLs,asins,...,imageURLs,keys,manufacturer,manufacturerNumber,name,primaryCategories,sourceURLs,upc,weight,price
0,AVphrugr1cnluZ0-FOeH,Yes,New,USD,"2017-05-10T20:00:00Z,2017-05-09T15:00:00Z",False,Bestbuy.com,NaN,http://www.bestbuy.com/site/products/7100293.p...,B00I9HD8PK,...,https://i5.walmartimages.com/asr/dd5f42c4-076c...,"819127010485,ecoxgearecostonebluetoothspeaker/...",Ecoxgear,GDI-EGST701,EcoXGear Ecostone Bluetooth Speaker,Electronics,http://www.walmart.com/ip/EcoXGear-Ecostone-Bl...,8.19E+11,3 pounds,92.99
1,AVrI6FDbv8e3D1O-lm4R,Yes,New,USD,"2017-10-10T02:00:00Z,2017-08-12T03:00:00Z,2017...",False,Bestbuy.com,NaN,https://www.bestbuy.com/site/lenovo-100s-14ibr...,B06ZY63J8H,...,https://i5.walmartimages.com/asr/fcc50cce-a3c1...,"190793918948,lenovo100s14ibr14laptopintelceler...",NaN,100s-14ibr,Lenovo - 100S-14IBR 14 Laptop - Intel Celeron ...,Electronics,https://www.walmart.com/ip/Lenovo-100S-14IBR-1...,1.91E+11,4.3 pounds,229.99
2,AVpiLlubilAPnD_xBoTa,Yes,New,USD,"2017-10-10T19:00:00Z,2017-09-12T14:00:00Z,2017...",False,Bestbuy.com,NaN,https://www.bestbuy.com/site/house-of-marley-s...,B00G3P9UMU,...,https://i5.walmartimages.com/asr/c124aa15-b9e3...,"0846885007037,houseofmarleysmilejamaicainearea...",House Of Marley,EM-JE041-MI,House of Marley Smile Jamaica In-Ear Earbuds,Electronics,https://www.walmart.com/ip/House-of-Marley-Smi...,8.47E+11,0.6 ounces,16.99
3,AVpgQP5vLJeJML43LQbd,Yes,New,USD,"2017-09-08T05:00:00Z,2017-09-18T13:00:00Z,2017...",False,Bestbuy.com,NaN,https://www.bestbuy.com/site/products/6311012....,B00TTWZFFA,...,https://i5.walmartimages.com/asr/1be435f7-5f3a...,"sonyultraportablebluetoothspeaker/sosrsx11bk,s...",Sony,SRSX11/BLK,Sony Ultra-Portable Bluetooth Speaker,Electronics,https://www.walmart.com/ip/Sony-Ultra-Portable...,27242886599,1 pounds,69.99
4,AV1YDsmoGV-KLJ3adcbe,More on the Way,New,USD,2017-12-05T13:00:00Z,True,bhphotovideo.com,Free Expedited Shipping for most orders over $49,https://www.bhphotovideo.com/c/product/1105014...,B00MHPAF38,...,http://i.ebayimg.com/thumbs/images/g/TBUAAOSwd...,sonyalphaa5100digitalcamerakitwith1650mmlenswh...,NaN,ILCE5100L/W,Alpha a5100 Mirrorless Digital Camera with 16-...,Electronics,https://reviews.bestbuy.com/3545/8429343/revie...,27242883246,9.98 oz 4.09 oz,846.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5431,AVqVGlGynnc1JgDc3jIv,Yes,New,USD,"2017-03-30T05:00:00Z,2017-03-30T11:00:00Z",False,Bestbuy.com,NaN,http://www.bestbuy.com/site/apple-iphone-se-16...,B01GUY5KYA,...,https://i5.walmartimages.com/asr/21d8b9a9-779a...,"888462804011,appleiphonesegold16gbforsprintmly...",NaN,MLY92LL/A,Apple iPhone SE Gold 16GB for Sprint ( MLY92LL...,Electronics,https://www.amazon.com/Apple-iPhone-SE-Gold-Sp...,8.88E+11,8 ounces,12.45
5432,AVpfUijE1cnluZ0-ikFo,In Stock,New,USD,"2017-12-07T08:00:00Z,2017-12-04T22:00:00Z,2017...",True,bhphotovideo.com,Free Expedited Shipping,https://www.bhphotovideo.com/c/product/1242562...,B00P7TQQZM,...,https://i5.walmartimages.com/asr/9431a090-b9a8...,zaggruggedfoliokeyboardcaseforappleipadair2bla...,Zagg,ID6RGKBB0,Rugged Book Keyboard and Case for iPad Air 2,Electronics,http://reviews.bestbuy.com/3545/9869101/review...,8.48E+11,25.6 ounces,149.99
5433,AV1YHulm-jtxr-f31Ndj,Yes,New,USD,2017-08-10T02:00:00Z,False,Bestbuy.com,NaN,http://www.bestbuy.com/site/360fly-4k-action-c...,B01G95INDK,...,https://pisces.bbystatic.com/image2/BestBuy_US...,360fly4kvideocamera10pieceeverythingyouneedbun...,NaN,FLYC4KC01BEN,4K Video Camera,Electronics,https://www.walmart.com/ip/360fly-4K-Video-Cam...,8.53E+11,6 oz,324.99
5434,AVpgIu4Q1cnluZ0-xBK-,In Stock,New,USD,2017-12-08T01:00:00Z,False,Hotelectronics,Value,https://www.walmart.com/ip/Alpine-5x7-Coaxial-...,B004UC2N7M,...,https://i5.walmartimages.com/asr/096a1bde-9994...,"793276601629,alpine5x72waycoaxialcarspeakerswi...",Alpine,SPS-517,"Alpine - 5 x 7"" 2-Way Coaxial Car Speakers wit...",Electronics,http://reviews.bestbuy.com/3545/1807145/review...,7.93E+11,2.7 Kg,61.55
5435,AVpfHcah1cnluZ0-eQLY,In Stock,New,USD,"2018-03-24T00:00:00Z,2018-03-19T18:00:00Z",True,Electronics Expo (Authorized Dealer),Value,https://www.walmart.com/ip/Pioneer-SP-FS52-130...,B008NCD2S4,...,http://i.ebayimg.com/images/g/MZoAAOSwT6pVuAY2...,"pioneer/spfs52,spfs52andrewjonesdesignedfloors...",Pioneer,SPFS52,SP-FS52 Andrew Jones Designed Floorstanding Lo...,Electronics,http://reviews.bestbuy.com/3545/5086937/review...,12562906102,25.8 lb,249.99

In [5]:
df.shape

(5436, 25)

In [6]:
df.isnull().sum()

id                        0
prices.availability       0
prices.condition          0
prices.currency           0
prices.dateSeen           0
prices.isSale             0
prices.merchant           0
prices.shipping        2237
prices.sourceURLs         0
asins                     0
brand                     0
categories                0
dateAdded                 0
dateUpdated               0
ean                    4261
imageURLs                 0
keys                      0
manufacturer           2959
manufacturerNumber        0
name                      0
primaryCategories         0
sourceURLs                0
upc                       0
weight                    0
price                     0
dtype: int64

In [7]:
df.describe()

             price
count  5436.000000
mean    492.941161
std     769.246463
min       1.000000
25%      79.950000
50%     194.410000
75%     486.952500
max    6999.990000

In [8]:
from sklearn.model_selection import train_test_split

x = df[["weight"]]
y = df["price"]

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

print("Số dòng tập huấn luyện:", len(x_train))
print("Số dòng tập kiểm tra:", len(x_test))

Số dòng tập huấn luyện: 4348
Số dòng tập kiểm tra: 1088