# BÀI TẬP: MEDICAL INSURANCE COST
**Nguồn:** kaggle.com/datasets/mosapabdelghany/medical-insurance-cost-dataset

## Setup

In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')


csv_path = 'https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

## A.2. Missing values & Duplicate data

In [3]:
print("Kiểm tra dữ liệu bị thiếu")
print(df.isnull().sum())

print("\nKiểm tra trùng lặp")
print(df.duplicated().sum())

Kiểm tra dữ liệu bị thiếu
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

Kiểm tra trùng lặp
1

## A.3. Invalid values

In [4]:
print("Age không hợp lệ:")
print(df[df['age'] <= 0])

print("\nBMI không hợp lệ:")
print(df[df['bmi'] <= 0])

print("\nChildren không hợp lệ:")
print(df[df['children'] < 0])

print("\nCharges không hợp lệ:")
print(df[df['charges'] <= 0])

print("\nSex không hợp lệ:")
print(df[~df['sex'].isin(['male', 'female'])])

print("\nSmoker không hợp lệ:")
print(df[~df['smoker'].isin(['yes', 'no'])])

print("\nRegion không hợp lệ:")
print(df[~df['region'].isin(['southwest', 'southeast', 'northwest', 'northeast'])])

Age không hợp lệ:
Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

BMI không hợp lệ:
Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

Children không hợp lệ:
Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

Charges không hợp lệ:
Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

Sex không hợp lệ:
Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

Smoker không hợp lệ:
Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

Region không hợp lệ:
Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

## A.4. Create a new column
Tạo cột `bmi_group`: Normal (<25), Overweight (25-30), Obese (>=30).

In [5]:
df['bmi_group'] = df['bmi'].apply(
    lambda x: 'Normal' if x < 25 else ('Obese' if x >= 30 else 'Overweight')
)
df[['bmi', 'bmi_group']]

         bmi   bmi_group
0     27.900  Overweight
1     33.770       Obese
2     33.000       Obese
3     22.705      Normal
4     28.880  Overweight
...      ...         ...
1333  30.970       Obese
1334  31.920       Obese
1335  36.850       Obese
1336  25.800  Overweight
1337  29.070  Overweight

[1338 rows x 2 columns]

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [10]:
numeric_cols = ['age', 'bmi', 'children', 'charges']

for col in numeric_cols:
    print(f"\n--- {col} ---")
    print("Mean:", df[col].mean())
    print("Median:", df[col].median())
    print("Mode:", df[col].mode().tolist())

--- age ---
Mean: 39.20702541106129
Median: 39.0
Mode: [18]

--- bmi ---
Mean: 30.66339686098655
Median: 30.4
Mode: [32.3]

--- children ---
Mean: 1.0949177877429
Median: 1.0
Mode: [0]

--- charges ---
Mean: 13270.422265141257
Median: 9382.033
Mode: [1639.5631]

## Group 2 — Dispersion

In [ ]:
for col in numeric_cols:
    print(f"\n--- {col} ---")
    
    print("Range:", df[col].max() - df[col].min())
    print("Variance:", df[col].var())
    print("Standard deviation:", df[col].std())
    print("IQR:", df[col].quantile(0.75) - df[col].quantile(0.25))

--- age ---
Range: 46
Variance: 197.40138665754375
Standard deviation: 14.049960379216154
IQR: 24.0

--- bmi ---
Range: 37.17
Variance: 37.18788360977323
Standard deviation: 6.098186911679014
IQR: 8.3975

--- children ---
Range: 5
Variance: 1.453212745666905
Standard deviation: 1.205492739781914
IQR: 2.0

--- charges ---
Range: 62648.554110000005
Variance: 146652372.15285498
Standard deviation: 12110.011236694001
IQR: 11899.625365

## Group 3 — Location and Shape

In [12]:
for col in numeric_cols:
    print(f"\n--- {col} ---")
    
    print("Min:", df[col].min())
    print("Q1:", df[col].quantile(0.25))
    print("Median:", df[col].median())
    print("Q3:", df[col].quantile(0.75))
    print("Max:", df[col].max())
    print("Skewness:", df[col].skew())
    print("Kurtosis:", df[col].kurt())

--- age ---
Min: 18
Q1: 27.0
Median: 39.0
Q3: 51.0
Max: 64
Skewness: 0.05567251565299186
Kurtosis: -1.2450876526418673

--- bmi ---
Min: 15.96
Q1: 26.29625
Median: 30.4
Q3: 34.69375
Max: 53.13
Skewness: 0.2840471105987448
Kurtosis: -0.05073153135467834

--- children ---
Min: 0
Q1: 0.0
Median: 1.0
Q3: 2.0
Max: 5
Skewness: 0.9383804401702414
Kurtosis: 0.2024541467168901

--- charges ---
Min: 1121.8739
Q1: 4740.28715
Median: 9382.033
Q3: 16639.912515
Max: 63770.42801
Skewness: 1.5158796580240388
Kurtosis: 1.6062986532967907

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Người hút thuốc trả chi phí cao hơn bao nhiêu lần so với người không hút, và có đồng đều giữa các vùng không?

In [20]:
TB = df.groupby('smoker')['charges'].mean()
print(TB)

ty_le = TB['yes'] / TB['no']
print(f"Người hút thuốc lá phải trả cao hơn khoảng {ty_le:.2f} lần")

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64
Người hút thuốc lá phải trả cao hơn khoảng 3.80 lần

In [26]:
vung = df.groupby(['region', 'smoker'])['charges'].mean().unstack()
print(vung)

vung['ty_le'] = vung['yes'] / vung['no']
print("\nTỷ lệ người hút / người không hút theo vùng:")
print(vung['ty_le'].sort_values(ascending=False))

smoker              no           yes
region
northeast  9165.531672  29673.536473
northwest  8556.463715  30192.003182
southeast  8032.216309  34844.996824
southwest  8019.284513  32269.063494

Tỷ lệ người hút / người không hút theo vùng:
region
southeast    4.338155
southwest    4.023933
northwest    3.528561
northeast    3.237514
Name: ty_le, dtype: float64

## Câu hỏi 2: BMI có tương quan với chi phí mạnh hơn ở nhóm hút thuốc hay không hút thuốc?

In [29]:
ng_hut = df[df['smoker'] == 'yes'][['bmi', 'charges']].corr().loc['bmi', 'charges']
k_hut = df[df['smoker'] == 'no'][['bmi', 'charges']].corr().loc['bmi', 'charges']

print(f"Người hút thuốc: {ng_hut:.4f}")
print(f"Người không hút thuốc: {k_hut:.4f}")
if abs(ng_hut) > abs(k_hut):
    print("BMI có tương quan mạnh hơn với chi phí ở nhóm hút thuốc")
else:
    print("BMI có tương quan mạnh hơn với chi phí ở nhóm không hút thuốc")

Người hút thuốc: 0.8065
Người không hút thuốc: 0.0840
BMI có tương quan mạnh hơn với chi phí ở nhóm hút thuốc

## Câu hỏi 3: Vùng nào có chi phí bảo hiểm trung bình cao nhất?

In [31]:
tb_vung = df.groupby('region')['charges'].mean().sort_values(ascending = False)
print(tb_vung)
print(f"Vùng có chi phí bảo hiểm trung bình cao nhất: {tb_vung.index[0]}")

region
southeast    14735.411438
northeast    13406.384516
northwest    12417.575374
southwest    12346.937377
Name: charges, dtype: float64
Vùng có chi phí bảo hiểm trung bình cao nhất: southeast

## Câu hỏi 4: Số lượng con cái có làm tăng chi phí bảo hiểm không?

In [38]:
tb_concai = df.groupby('children')['charges'].mean()
print(tb_concai)
tg_quan_con = df[['children', 'charges']].corr().loc['children', 'charges']
print(f"\nTương quan giữa số con và chi phí: {tg_quan_con:.4f}")

children
0    12365.975602
1    12731.171832
2    15073.563734
3    15355.318367
4    13850.656311
5     8786.035247
Name: charges, dtype: float64

Tương quan giữa số con và chi phí: 0.0680

## Câu hỏi 5: Tuổi có tương quan với chi phí bảo hiểm không?

In [40]:
tg_quan_tuoi = df[['age', 'charges']].corr().loc['age', 'charges']
print(f"\nTương quan giữa tuổi và chi phí: {tg_quan_tuoi:.4f}")

Tương quan giữa tuổi và chi phí: 0.2990

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể.

Người hút thuốc có chi phí bảo hiểm cao hơn khoảng 3,8 lần so với người không hút. BMI có tương quan với chi phí mạnh hơn ở nhóm hút thuốc. Southeast là khu vực có chi phí bảo hiểm trung bình cao nhất. Số con gần như không ảnh hưởng đến chi phí, trong khi tuổi có xu hướng làm chi phí tăng